title: Çağatay Altuntaş | Academic Portfolio
email: caltuntas@itu.edu.tr
description: >-
  Academic portfolio of Çağatay Altuntaş, Ph.D. in Mathematics.
baseurl: ""
url: "https://cagatayaltuntas.github.io"
